# spell-checker: disable
---
name: release-please

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        uses: GoogleCloudPlatform/release-please-action@v3.7.3
        with:
          release-type: terraform-module
